### ISSUE TITLE
Ob Hit affects appear completely disabled in the latest mode version for all characters

### ISSUE THREAD

**Issue by Bbridgewa** [1TeaL/DekuRor2#6]
In singleplayer and multiplayer, just having the mod installed causes the following effects to never proc:

Firebolt Fire
Bleed
Plasma shrimp
Missiles
Polylute
Ukalale
etc. 

Just none of them work.
(mod version 4.0.0)
(game version 1.4.2.1)

**Comment by 1TeaL** [comment]
Could you provide a lot and a modlist? Thanks

**Comment by 1TeaL** [comment]
Fixed the issue in 4.0.1
