### ISSUE TITLE
BlackWhip tick dmg isn't working, neither is the healing

### ISSUE THREAD

**Issue by dragrider2** [1TeaL/DekuRor2#7]
I am playing with 108 mods so I do think one of them is interfering, but at the moment I don't know which one it could be

Currently when I activate it binds the creatures in place, but doesn't do any tick damage or healing.

No idea what it could be.

**Comment by 1TeaL** [comment]
Hey, can you upload your log file?

**Comment by dragrider2** [comment]
Where can I find that log file?

**Comment by 1TeaL** [comment]
Hey, from r2modman go to settings-> locations-> browse profile folder-> click into bepin ex folder and see the logoutput.log? that's the one. I do see the issue of it not working and I'll aim to fix it.

**Comment by dragrider2** [comment]
[LogOutput.log](https://github.com/1TeaL/DekuRor2/files/11067350/LogOutput.log)
There is the log
and thank you for fixing the issue so quickly!

**Comment by 1TeaL** [comment]
Thanks for the log, and no worries lmk if you have any issues!
